# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/file_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/file_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/file_processor.proto\x12\x0e\x66ile_processor\"6\n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\"`\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x04 \x01(\x0c\"C\n\tFileChunk\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\x32\xbc\x02\n\rFileProcessor\x12H\n\x0b\x43ompressPDF\x12\x1b.file_processor.FileRequest\x1a\x1c.file_processor.FileResponse\x12H\n\x0c\x43onvertToTXT\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12N\n\x12\x43onvertImageFormat\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x12G\n\x0bResizeImage\x12\x19.file_processor.FileChunk\x1a\x19.file_processor.FileChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.file_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=46
  _globals['_FILEREQUEST']._serialized_end=100
  _globals['_FILERESPONSE']._serialized_start=102
  _globals['_FILERESPONSE']._serialized_end=198
  _globals['_FILECHUNK']._serialized_start=200
  _globals['_FILECHUNK']._serialized_end=267
  _globals['_FILEPROCESSOR']._serialized_start=270
  _globals['_FILEPROCESSOR']._serialized_end=586
# @@protoc_insertion_point(module_scope)
